Fix run_tests.yml when pitest fails on previous commit

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -33,7 +33,7 @@ jobs:
         uses: actions/github-script@v7
         with:
           script: |
-            const body = `❌ Tests failed. Here's a RickRoll for you:\n ![Rickroll](https://raw.githubusercontent.com/charliepain/graphhopper/af7981f933f355980a0f64b4bc274f2ed6a11479/rickroll/rickroll.gif)`;
+            const body = `❌ A test case has failed. Here's a RickRoll for you:\n ![Rickroll](https://raw.githubusercontent.com/charliepain/graphhopper/af7981f933f355980a0f64b4bc274f2ed6a11479/rickroll/rickroll.gif)`;
 
             if (context.payload.pull_request) {
               // On a PR
@@ -52,6 +52,9 @@ jobs:
                 body,
               });
             }
+            
+            echo "A test case has failed"
+            exit 1
 
       - name: Build required modules for pitest
         run: |
@@ -79,10 +82,7 @@ jobs:
 
           # Run pitest on core module
           cd core
-          if ! mvn -B test-compile org.pitest:pitest-maven:mutationCoverage; then
-            echo "pitest failed on the previous commit. No comparison can be made."
-            exit 0
-          fi
+          mvn -B test-compile org.pitest:pitest-maven:mutationCoverage
           CURRENT_CORE_SCORE=$(python3 ../.github/scripts/extract_mutation_score.py target/pit-reports)
           cd ..
 
@@ -95,13 +95,19 @@ jobs:
 
           # Run pitest on web-api module (previous commit)
           cd web-api
-          mvn -B test-compile org.pitest:pitest-maven:mutationCoverage
+          if ! mvn -B test-compile org.pitest:pitest-maven:mutationCoverage; then
+            echo "pitest failed on previous commit. Cannot make comparison."
+            exit 0
+          fi
           PREVIOUS_WEB_API_SCORE=$(python3 ../.github/scripts/extract_mutation_score.py target/pit-reports)
           cd ..
 
           # Run pitest on core module (previous commit)
           cd core
-          mvn -B test-compile org.pitest:pitest-maven:mutationCoverage
+          if ! mvn -B test-compile org.pitest:pitest-maven:mutationCoverage; then
+            echo "pitest failed on previous commit. Cannot make comparison."
+            exit 0
+          fi
           PREVIOUS_CORE_SCORE=$(python3 ../.github/scripts/extract_mutation_score.py target/pit-reports)
           cd ..
 
